version: '3.8'
services:
    nextjs:
        env_file:
            - ./.env.local
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: 'imperfectcm/motto_design:latest'
        ports:
            - "3000:3000"
        depends_on:
            - pocketbase
        environment:
            - POCKETBASE_URL=http://pocketbase:8090
    pocketbase:
        build:
            context: .
            args:
                - VERSION=0.22.22 # <--------- Set the Pocketbase version here. It will be downloaded from their GitHub repo
        image: 'imperfectcm/pocketbase:latest'
        container_name: pocketbase
        restart: unless-stopped
        ports:
            - "8090:8090"
        volumes:
            - ./pb_data:/pb_data
            - ./pb_migrations:/pb_migrations
        command: ./pocketbase serve --http=0.0.0.0:8090 --dir /pb_data
        healthcheck:
            #optional (recommended) since v0.10.0
            test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
            interval: 5s
            timeout: 5s
            retries: 5
