version: "3.7"
services:
    nextjs:
        env_file:
            - ./.env.local
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: 'imperfectcm/motto_design:latest'
        ports:
            - "3000:3000"
    pocketbase:
        depends_on:
            - nextjs
        build:
            context: ./
            args:
                - VERSION=0.22.22 # <--------- Set the Pocketbase version here. It will be downloaded from their GitHub repo
        image: 'imperfectcm/pocketbase:latest'
        container_name: pocketbase
        restart: unless-stopped
        command: ./pocketbase serve
        ports:
            - "8090:8090"
        volumes:
            - /path/to/data:/pb_data
            - /path/to/public:/pb_public #optional
            - /path/to/hooks:/pb_hooks #optional
        healthcheck:
            #optional (recommended) since v0.10.0
            test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
            interval: 5s
            timeout: 5s
            retries: 5
