name: motto_design
on: 
  push:
    branches:
      - "production"
    workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    container: docker:20.10.21-alpine3.16
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
      - run: |
        yarn install
        yarn test

  build-server:
    runs-on: ubuntu-latest
    container: docker:20.10.21-alpine3.16
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build and Push
        env:
          WEB_URL: http://localhost:3000
          POCKETBASE_URL: http://localhost:8090
        run: |
          docker build -t imperfectcm/motto_design:latest .
          docker push imperfectcm/motto_design:latest

  deploy-server:
    needs: build-server
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: motto-intdesign.com
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ubuntu
          script: |
            docker compose pull
            docker compose up -d
            docker image prune -f